name: build-on-push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  checks: write
  pull-requests: write
  contents: write
  packages: write
  issues: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Generate and submit dependency graph
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: gradle/actions/dependency-submission@v4

      - name: Build for ${{ github.ref }}
        run: ./gradlew build --parallel

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          include_passed: true
          detailed_summary: true
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Save environment variables
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Publish Pepper BDD report
        if: ${{ always() && github.ref == 'refs/heads/main' }}
        run: | # language=shell script
          git fetch --unshallow origin gh-pages
          git checkout gh-pages
          git pull
          
          mkdir -p pepper-reports/${{ github.run_id }}
          cp -r pepper-bdd-sample/build/reports/pepper/* pepper-reports/${{ github.run_id }}

          jq '.suites += [{"name": "${{ env.NOW }}", "path":"${{ github.run_id }}"}]' pepper-reports/pepper-root.json > pepper-root_new.json
          cat pepper-root_new.json > pepper-reports/pepper-root.json

          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git add pepper-reports/${{ github.run_id }} pepper-reports/pepper-root.json
          git commit -m "Add Pepper BDD report for run ${{ github.run_id }}"
          git push
